# Generated by Django 6.0 on 2026-06-15
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], default='OTHER', help_text='Type of action performed', max_length=20)),
                ('module', models.CharField(blank=True, default='', help_text='Module/section where the action occurred (e.g., Attendance, Payroll, Employees)', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user when the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text="User agent string of the user's browser/device")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_owner', models.ForeignKey(blank=True, help_text='Admin owner for tenant isolation (auto-filled from user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
