# Generated by Django 5.0.14 on 2026-06-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0002_add_settings_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], default='OTHER', help_text='Type of action performed', max_length=20),
        ),
    ]
