# Generated by Django 5.0.14 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0003_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('VIEW', 'View'), ('SETTINGS', 'Settings'), ('OTHER', 'Other')], default='OTHER', help_text='Type of action performed', max_length=20),
        ),
    ]
