# Generated by Django 5.0.14 on 2026-01-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
