# Generated by Django 5.0.14 on 2026-01-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_employee_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_image',
        ),
    ]
