# Generated by Django 5.0.14 on 2026-01-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0008_employee_account_holder_name_employee_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bonus_amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bonus_eligible',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payment_frequency',
        ),
    ]
