# Generated by Django 5.0.14 on 2026-01-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0010_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields defined by the client'),
        ),
    ]
