# Generated by Django 5.0.14 on 2026-01-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0011_employee_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='custom_fields',
        ),
    ]
