# Generated by Django 5.0.14 on 2026-01-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0014_remove_employee_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Internal field name (no spaces)', max_length=100)),
                ('field_label', models.CharField(help_text='Display label for the field', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('field_options', models.TextField(blank=True, help_text="For dropdown fields: comma-separated options (e.g., 'Option1,Option2,Option3')")),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'field_label'],
                'unique_together': {('field_name',)},
            },
        ),
    ]
