# Generated by Django 5.0.14 on 2026-01-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0015_employee_custom_fields_customfielddefinition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFieldDefinition',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='custom_fields',
        ),
    ]
