# Generated by Django 5.0.14 on 2026-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0017_employee_custom_fields_customfielddefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(choices=[('in_office', 'In Office'), ('out_of_office', 'Out of Office')], default='in_office', max_length=20),
        ),
    ]
