# Generated by Django 5.0.14 on 2026-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0018_employee_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_pf_contribution',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Employee PF contribution percentage or fixed amount', max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer_pf_contribution',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Employer PF contribution percentage or fixed amount', max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='max_overtime_hours_per_month',
            field=models.DecimalField(decimal_places=1, default=40.0, help_text='Maximum allowed overtime hours per month', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime multiplier (e.g. 1.5) or fixed hourly rate', max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate_type',
            field=models.CharField(blank=True, choices=[('multiplier', 'Multiplier (e.g. 1.5x)'), ('fixed', 'Fixed Amount per Hour')], default='multiplier', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_contribution_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage of Basic'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('general', 'General  (9 AM – 6 PM)'), ('morning', 'Morning  (6 AM – 2 PM)'), ('afternoon', 'Afternoon (2 PM – 10 PM)'), ('night', 'Night    (10 PM – 6 AM)'), ('custom', 'Custom')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_off_days',
            field=models.CharField(blank=True, default='Saturday,Sunday', help_text="Comma-separated off days, e.g. 'Saturday,Sunday'", max_length=100),
        ),
    ]
