# Generated by Django 5.0.14 on 2026-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0019_employee_employee_pf_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
