# Generated by Django 5.0.14 on 2026-04-06 04:58

import employee_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0021_employeeasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=employee_management.models.R2EmployeeImageStorage(), upload_to='employee_images/'),
        ),
    ]
