# Generated by Django 5.0.14 on 2026-04-28 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0023_alter_customfielddefinition_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='increment_reminder_days',
            field=models.PositiveIntegerField(default=30, help_text='Send a reminder this many days before the next increment date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='increment_reminder_sent',
            field=models.BooleanField(default=False, help_text='Set to True once the upcoming-increment reminder has been dispatched'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_increment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount (absolute) of the last salary increment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_increment_date',
            field=models.DateField(blank=True, help_text='Date when the last salary increment was applied', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_increment_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of the last salary increment', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_increment_date',
            field=models.DateField(blank=True, help_text='Scheduled date for the next salary increment', null=True),
        ),
        migrations.CreateModel(
            name='SalaryIncrementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_date', models.DateField(help_text='Date the increment was applied')),
                ('old_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_percentage', models.DecimalField(decimal_places=2, help_text='Calculated as (increment_amount / old_salary) * 100', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_increments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_history', to='employee_management.employee')),
            ],
            options={
                'ordering': ['-increment_date'],
            },
        ),
    ]
