# Generated by Django 5.0.14 on 2026-04-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0024_employee_increment_reminder_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='increment_reminder_days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='increment_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_increment_amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_increment_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_increment_percentage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_increment_date',
        ),
        migrations.DeleteModel(
            name='SalaryIncrementHistory',
        ),
    ]
