# Generated by Django 5.0.14 on 2026-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0025_remove_employee_increment_reminder_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_increment_date',
            field=models.DateField(blank=True, help_text='Date when the last salary increment was applied', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_increment_date',
            field=models.DateField(blank=True, help_text='Scheduled date for the next salary increment', null=True),
        ),
    ]
