# Generated by Django 5.0.14 on 2026-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0026_employee_last_increment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='increment_cycle_months',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Every Month'), (2, 'Every 2 Months'), (3, 'Every Quarter (3 Months)'), (4, 'Every 4 Months'), (6, 'Every 6 Months (Half-Yearly)'), (12, 'Every Year (Annual)'), (18, 'Every 18 Months'), (24, 'Every 2 Years'), (0, 'Custom / Manual')], help_text='How often this employee receives a salary increment (in months). 0 = manual/custom, null = not configured.', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='next_increment_date',
            field=models.DateField(blank=True, help_text='Scheduled date for the next salary increment. Auto-calculated from last_increment_date + increment_cycle_months when saved.', null=True),
        ),
    ]
