# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0028_salaryincrementhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementhistory',
            name='increment_cycle_months',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Every Month'), (2, 'Every 2 Months'), (3, 'Every Quarter (3 Months)'), (4, 'Every 4 Months'), (6, 'Every 6 Months (Half-Yearly)'), (12, 'Every Year (Annual)'), (18, 'Every 18 Months'), (24, 'Every 2 Years'), (0, 'Custom / Manual')], null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementhistory',
            name='next_increment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
