# Generated by Django 5.0.14 on 2026-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0029_salaryincrementhistory_increment_cycle_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='Auto-calculated from date_of_joining + probation_period_months when saved.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_period_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duration of the probation period in months (e.g. 3 or 6). Leave blank if no probation applies.', null=True),
        ),
    ]
