# Generated by Django 5.0.14 on 2026-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0030_employee_probation_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_start_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weekly_off_days',
        ),
        migrations.AddField(
            model_name='employee',
            name='duty_end_time',
            field=models.TimeField(blank=True, help_text='Employee duty end time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='duty_start_time',
            field=models.TimeField(blank=True, help_text='Employee duty start time', null=True),
        ),
    ]
