# Generated by Django 5.0.14 on 2026-05-30 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0031_remove_employee_shift_end_time_and_more'),
        ('master', '0013_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='master.section'),
        ),
    ]
