# Generated by Django 5.0.14 on 2026-06-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0032_employee_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
