# Generated by Django 5.0.14 on 2026-06-02 05:07

import django.db.models.deletion
import employee_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0033_add_gender_to_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('educational', 'Educational Certificate'), ('experience', 'Experience Certificate'), ('offer_letter', 'Offer Letter'), ('joining_letter', 'Joining Letter'), ('contract', 'Contract / Agreement'), ('nda', 'NDA'), ('insurance', 'Insurance Document'), ('medical', 'Medical Certificate'), ('payslip', 'Payslip'), ('bank_document', 'Bank Document'), ('visa', 'Visa / Work Permit'), ('passport', 'Passport Copy'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(help_text='Descriptive name for the document', max_length=255)),
                ('file', models.FileField(storage=employee_management.models.R2EmployeeImageStorage(), upload_to='employee_documents/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee_management.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
