# Generated by Django 5.0.14 on 2026-03-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watsapp_config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNumber',
        ),
        migrations.DeleteModel(
            name='NotificationPurpose',
        ),
        migrations.DeleteModel(
            name='WhatsAppConfig',
        ),
    ]
