# Generated by Django 5.0.14 on 2026-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watsapp_config', '0002_delete_adminnumber_delete_notificationpurpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAdminNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(default='HR Manager', max_length=100)),
                ('purposes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ultramsg', 'UltraMsg'), ('waapi', 'WaAPI'), ('twilio', 'Twilio'), ('meta', 'Meta Cloud API'), ('wablas', 'Wablas'), ('custom', 'Custom / Other')], default='ultramsg', max_length=20)),
                ('instance_id', models.CharField(blank=True, max_length=255)),
                ('api_token', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('webhook_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Config',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNotificationPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('send_to_employee', models.BooleanField(default=True)),
                ('send_to_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
