# Generated by Django 5.0.14 on 2026-04-08 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsapp_config', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappadminnumber',
            name='admin_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_admin_numbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='admin_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappnotificationpurpose',
            name='admin_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_purposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationpurpose',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappnotificationpurpose',
            unique_together={('key', 'admin_owner')},
        ),
    ]
