# Generated by Django 5.0.14 on 2026-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsapp_config', '0005_add_dxing_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconfig',
            name='provider',
            field=models.CharField(choices=[('ultramsg', 'UltraMsg'), ('waapi', 'WaAPI'), ('twilio', 'Twilio'), ('meta', 'Meta Cloud API'), ('wablas', 'Wablas'), ('custom', 'Custom / Other')], default='ultramsg', max_length=20),
        ),
    ]
