# Generated by Django 5.0.14 on 2026-03-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_location',
            field=models.CharField(choices=[('IN_OFFICE', 'In Office'), ('OUT_OF_OFFICE', 'Out of Office')], default='IN_OFFICE', max_length=20),
        ),
    ]
