# Generated by Django 5.0.14 on 2026-04-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
