# Generated by Django 5.0.14 on 2026-04-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_user_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_id',
        ),
    ]
