# Generated by Django 5.0.14 on 2026-04-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_user_client_id_user_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
    ]
