# Generated by Django 5.0.14 on 2026-04-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_user_client_id_remove_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
