# Generated by Django 5.0.14 on 2026-04-07 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_user_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
