# Generated by Django 5.0.14 on 2026-05-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
