# Generated by Django 5.0.14 on 2026-05-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_user_company_setup_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_setup_completed',
        ),
    ]
