# Generated by Django 5.0.14 on 2026-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_user_is_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_switch_client',
            field=models.BooleanField(default=True),
        ),
    ]
