# Generated by Django 5.2.4 on 2025-12-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('skills', models.JSONField(default=list)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('status', models.CharField(choices=[('uploaded', 'CV Uploaded'), ('interview', 'Interview'), ('interview1', 'Interview 1'), ('interview2', 'Interview 2'), ('pending', 'Decision Pending'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
