# Generated by Django 5.0.14 on 2026-01-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.PositiveSmallIntegerField(default=0)),
                ('knowledge', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('attitude', models.PositiveSmallIntegerField(default=0)),
                ('communication', models.PositiveSmallIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='HR.candidate')),
            ],
        ),
    ]
