# Generated by Django 5.0.14 on 2026-02-21 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_candidaterating'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('offer_date', models.DateField(auto_now_add=True)),
                ('work_location', models.CharField(blank=True, max_length=200)),
                ('work_hours', models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=100)),
                ('company_name', models.CharField(blank=True, default='Our Company', max_length=200)),
                ('hr_name', models.CharField(blank=True, max_length=200)),
                ('hr_designation', models.CharField(blank=True, default='HR Manager', max_length=200)),
                ('additional_benefits', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='HR.candidate')),
            ],
        ),
    ]
