# Generated by Django 5.0.14 on 2026-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_offerletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
