# Generated by Django 5.0.14 on 2026-04-06 04:58

import HR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_pipelinestage_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(storage=HR.models.R2HRStorage(), upload_to='cvs/'),
        ),
    ]
