# Generated by Django 5.0.14 on 2026-04-08 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_alter_candidate_cv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='admin_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='admin_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_stages', to=settings.AUTH_USER_MODEL),
        ),
    ]
