# Generated by Django 5.0.14 on 2026-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_candidate_admin_owner_pipelinestage_admin_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
