# Generated by Django 5.0.14 on 2026-05-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_candidate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='date',
        ),
    ]
