# Generated by Django 5.0.14 on 2026-05-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_remove_candidate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
