# Generated by Django 5.0.14 on 2026-05-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_candidate_interview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='interview_date',
        ),
    ]
