# Generated by Django 5.0.14 on 2026-05-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_remove_candidate_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
