# Generated by Django 5.0.14 on 2026-02-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_leavetype_created_by_leavetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the leave type', null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this leave type is currently active'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(help_text='Name of the leave type', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='leavetype',
            table='employee_leave_type',
        ),
    ]
