# Generated by Django 5.0.14 on 2026-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_leavetype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the leave type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(help_text='Name of the leave type (e.g., Sick Leave, Annual Leave)', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='leavetype',
            table='master_leave_types',
        ),
    ]
