# Generated by Django 6.0.2 on 2026-02-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_leavetype_description_alter_leavetype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='category',
            field=models.CharField(choices=[('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('special_leave', 'Special Leave'), ('mandatory_holiday', 'Mandatory Holiday')], default='casual_leave', help_text='Category of the leave/holiday', max_length=50),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='date',
            field=models.DateField(blank=True, help_text='Date for specific holidays (optional for ongoing allowances)', null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', help_text='Payment status for this leave type', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(help_text='Name of the leave/holiday (e.g., NEW YEARS DAY, ANNUAL LEAVE)', max_length=100, unique=True),
        ),
    ]
