# Generated by Django 6.0.1 on 2026-02-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0017_employee_custom_fields_customfielddefinition'),
        ('master', '0005_leavetype_category_leavetype_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_name', models.CharField(help_text='Name/Type of the allowance (e.g., Transport, Housing, Medical)', max_length=100)),
                ('year', models.IntegerField(help_text='Year for the allowance')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month for the allowance')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the allowance', max_digits=10)),
                ('description', models.TextField(blank=True, default='', help_text='Additional notes or description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this allowance is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee receiving the allowance', on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employee_management.employee')),
            ],
            options={
                'verbose_name': 'Allowance',
                'verbose_name_plural': 'Allowances',
                'db_table': 'master_allowances',
                'ordering': ['-year', '-month', 'employee__first_name'],
                'unique_together': {('employee', 'allowance_name', 'year', 'month')},
            },
        ),
    ]
