# Generated by Django 5.0.14 on 2026-03-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the holiday (e.g., Christmas Day)', max_length=150)),
                ('date', models.DateField(help_text='Date of the holiday')),
                ('type', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('company', 'Company'), ('optional', 'Optional')], default='national', help_text='Type of holiday', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or notes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holiday is currently visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'master_holidays',
                'ordering': ['date'],
            },
        ),
    ]
