# Generated by Django 5.0.14 on 2026-03-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement headline', max_length=255)),
                ('body', models.TextField(blank=True, default='', help_text='Full announcement details')),
                ('date', models.DateField(help_text='Announcement date')),
                ('tag', models.CharField(choices=[('general', 'General'), ('performance', 'Performance'), ('benefits', 'Benefits'), ('training', 'Training'), ('holiday', 'Holiday'), ('policy', 'Policy'), ('event', 'Event')], default='general', help_text='Category tag', max_length=20)),
                ('icon', models.CharField(default='📢', help_text='Emoji icon for this announcement', max_length=10)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of the list')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'master_announcements',
                'ordering': ['-is_pinned', '-date', '-created_at'],
            },
        ),
    ]
