# Generated by Django 5.0.14 on 2026-05-11 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_allowance_admin_owner_announcement_admin_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Job title name (e.g., Software Engineer, HR Manager)', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the job title')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this job title is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_owner', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Title',
                'verbose_name_plural': 'Job Titles',
                'db_table': 'master_job_titles',
                'ordering': ['name'],
                'unique_together': {('name', 'admin_owner')},
            },
        ),
    ]
