# Generated by Django 5.0.14 on 2026-05-25 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_jobtitle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_data', models.JSONField(default=dict, help_text='Full payroll-policy configuration (attendance, overtime, leave)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_owner', models.OneToOneField(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Policy',
                'verbose_name_plural': 'Payroll Policies',
                'db_table': 'master_payroll_policy',
            },
        ),
    ]
