# Generated by Django 5.0.14 on 2026-06-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_holiday_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days this announcement stays visible after its date. Leave blank for no expiry.', null=True),
        ),
    ]
