# Generated by Django 5.0.14 on 2026-02-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_remove_userpermission_user_menu_usermenuaccess_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
