# Generated by Django 5.0.14 on 2026-02-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_alter_userrole_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
