# Generated by Django 6.0.1 on 2026-02-24 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0017_employee_custom_fields_customfielddefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Payroll year')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Payroll month')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Basic salary from employee record', max_digits=10)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all allowances for this month', max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all deductions for this month', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Net salary after allowances and deductions', max_digits=10)),
                ('total_days_in_month', models.IntegerField(default=30, help_text='Total days in the month')),
                ('total_working_days', models.IntegerField(default=0, help_text='Total working days (based on attendance)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='Payroll status', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or remarks')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payroll was processed', null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was made', null=True)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Payment transaction reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee for this payroll record', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employee_management.employee')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed this payroll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'db_table': 'payroll',
                'ordering': ['-year', '-month', 'employee__first_name'],
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='payroll_employe_5ad3db_idx'), models.Index(fields=['status'], name='payroll_status_ac0f6a_idx')],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
