# Generated by Django 5.0.14 on 2026-02-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_late_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='late_approved_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_approved_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_request',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_request_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_request_status',
        ),
    ]
