# Generated by Django 5.0.14 on 2026-02-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_check_in_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_longitude',
        ),
    ]
