# Generated by Django 5.0.14 on 2026-02-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
