# Generated by Django 5.0.14 on 2026-03-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_latearrivalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office latitude – set this to enable geofence enforcement', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office longitude – set this to enable geofence enforcement', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='office_radius_meters',
            field=models.IntegerField(default=100, help_text='Allowed check-in/out radius in metres for IN_OFFICE users'),
        ),
    ]
