# Generated by Django 5.0.14 on 2026-03-27 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendancesettings_office_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_verified_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_verified_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='face_recognition_enabled',
            field=models.BooleanField(default=False, help_text='Require face verification during check-in and check-out'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office latitude – set to enable geofence enforcement', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office longitude – set to enable geofence enforcement', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField(help_text='JSON array of 128-dimensional face encoding vector')),
                ('reference_image', models.ImageField(blank=True, help_text='Optional reference photo for display purposes', null=True, upload_to='face_profiles/')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_face_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Face Profile',
                'verbose_name_plural': 'Employee Face Profiles',
            },
        ),
    ]
