# Generated by Django 5.0.14 on 2026-03-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_attendance_face_verified_checkin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='face_verified_checkin',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='face_verified_checkout',
        ),
        migrations.RemoveField(
            model_name='attendancesettings',
            name='face_recognition_enabled',
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office latitude – set this to enable geofence enforcement', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office longitude – set this to enable geofence enforcement', max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeFaceProfile',
        ),
    ]
