# Generated by Django 5.0.14 on 2026-04-08 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_earlydeparturerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='admin_owner',
            field=models.ForeignKey(blank=True, help_text='The admin/tenant who owns this attendance record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='admin_owner',
            field=models.ForeignKey(blank=True, help_text='The admin/tenant who owns these settings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_attendance_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earlydeparturerequest',
            name='admin_owner',
            field=models.ForeignKey(blank=True, help_text='The admin/tenant who owns this request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_early_departure_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='latearrivalrequest',
            name='admin_owner',
            field=models.ForeignKey(blank=True, help_text='The admin/tenant who owns this request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_late_arrival_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='admin_owner',
            field=models.ForeignKey(blank=True, help_text='The admin/tenant who owns this leave request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
