# Generated by Django 5.0.14 on 2026-04-17 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_attendance_admin_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.TextField(help_text='JSON-serialised face embedding vector produced by DeepFace ArcFace model.')),
                ('registered_image', models.ImageField(blank=True, help_text='Reference photo uploaded during face registration.', null=True, upload_to='face_encodings/')),
                ('model_name', models.CharField(default='ArcFace', help_text='DeepFace model used to generate this encoding.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_owner', models.ForeignKey(blank=True, help_text='The admin/tenant who owns this face encoding.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_face_encodings', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, help_text='Admin or the user themselves who registered the face.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_face_encodings', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
            },
        ),
    ]
