# Generated by Django 5.0.14 on 2026-04-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_faceencoding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceEncoding',
        ),
    ]
