# Generated by Django 5.0.14 on 2026-04-18 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_delete_faceencoding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField(help_text='Face embedding vector (list of floats) produced by DeepFace.')),
                ('face_image', models.ImageField(blank=True, help_text='Cropped face image used to generate this encoding.', null=True, upload_to='face_encodings/')),
                ('model_name', models.CharField(default='Facenet512', help_text='DeepFace model used to generate the encoding (e.g. Facenet512, ArcFace).', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_owner', models.ForeignKey(blank=True, help_text='The admin/tenant who owns this face encoding.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_face_encodings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'ordering': ['-created_at'],
            },
        ),
    ]
