# Generated by Django 5.0.14 on 2026-04-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_faceencoding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceEncoding',
        ),
    ]
