# Generated by Django 5.0.14 on 2026-04-18 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_delete_faceencoding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='Face embedding vector (list of floats) produced by DeepFace.')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_owner', models.ForeignKey(blank=True, help_text='The admin/tenant who owns this face record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_face_data', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The user whose face embedding is stored.', on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Face Data',
                'verbose_name_plural': 'Employee Face Data',
            },
        ),
    ]
