# Generated by Django 5.0.14 on 2026-04-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_add_employee_face_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeFaceData',
        ),
    ]
