# Generated by Django 5.0.14 on 2026-04-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_employeefacedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeFaceData',
        ),
    ]
