# Generated by Django 5.0.14 on 2026-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_employeefacedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefacedata',
            name='face_embedding',
            field=models.TextField(blank=True, help_text='JSON-serialised Facenet512 embedding vector (512 floats).', null=True),
        ),
    ]
