# Generated by Django 5.0.14 on 2026-05-05 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_remove_attendance_total_break_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_break_minutes',
            field=models.IntegerField(default=0, help_text='Total break duration in minutes for this day.'),
        ),
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.DateTimeField(help_text='When the break started.')),
                ('break_end', models.DateTimeField(blank=True, help_text='When the break ended (null = ongoing).', null=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Break duration in minutes (calculated on break_end).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_owner', models.ForeignKey(blank=True, help_text='The admin/tenant who owns this break record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_break_records', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(help_text='The attendance record this break belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Break Record',
                'verbose_name_plural': 'Break Records',
                'ordering': ['break_start'],
            },
        ),
    ]
