# Generated by Django 5.0.14 on 2026-05-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_attendance_total_break_minutes_breakrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total_break_minutes',
        ),
        migrations.DeleteModel(
            name='BreakRecord',
        ),
    ]
