# Generated by Django 5.0.14 on 2026-05-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_attendance_total_break_minutes_breakrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_type',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', help_text='Whether the leave is for a full day or half day.', max_length=10),
        ),
    ]
