# Generated by Django 5.0.14 on 2026-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_add_duration_type_to_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_out_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waived', 'Waived')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='earlydeparturerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='latearrivalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
    ]
