# Generated by Django 5.0.14 on 2026-06-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_attendance_check_out_waived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested advance amount in the local currency.', max_digits=12)),
                ('reason', models.TextField(help_text='Reason for requesting the salary advance.')),
                ('repayment_months', models.PositiveIntegerField(default=1, help_text='Number of months over which the advance will be repaid.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually approved (may differ from requested amount).', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_owner', models.ForeignKey(blank=True, help_text='The admin/tenant who owns this request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_salary_advance_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_salary_advances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Advance Request',
                'verbose_name_plural': 'Salary Advance Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
