# Generated by Django 5.0.14 on 2026-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_add_wfh_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_wfh',
            field=models.BooleanField(default=False, help_text='True if this attendance is for a work-from-home day.'),
        ),
    ]
