# Generated by Django 5.0.14 on 2026-06-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_add_is_wfh_to_attendance'),
        ('master', '0014_holiday_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type_obj',
            field=models.ForeignKey(blank=True, help_text='Reference to the admin-managed LeaveType record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='master.leavetype'),
        ),
    ]
