# Generated by Django 5.0.14 on 2026-06-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_attendancesettings_face_punch_enabled_normal_checkin_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_method',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('face', 'Face'), ('manual', 'Manual')], help_text="How the employee punched in: 'normal', 'face', or 'manual'.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_method',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('face', 'Face'), ('manual', 'Manual')], help_text="How the employee punched out: 'normal', 'face', or 'manual'.", max_length=10, null=True),
        ),
    ]
