# Generated by Django 5.0.14 on 2026-06-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_add_punch_method_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='face_break_enabled',
            field=models.BooleanField(default=False, help_text='When True employees can use face recognition to start/end breaks. Set to False to disable face-based break recording.'),
        ),
    ]
