# Generated by Django 5.0.14 on 2026-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_add_face_break_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='net_working_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours minus break time.', max_digits=5),
        ),
    ]
